name=StateMachine
version=1.0.1
author=Andrey Kolesov
maintainer=never-ya@yandex.ru
sentence=State Machine Library
paragraph=State Machine Library for any MC
category=State Control
url=https://github.com/AndyTakker/StateMachine
architectures=*
